### ISSUE TITLE
Capistrano > 3.7.0

### ISSUE THREAD

**Issue by 2ec0b4** [groovenauts/capistrano-systemd-multiservice#1]
Hello,
I'm looking for integrate a systemd task to my workflow and your work in this repository looks great but doesn't work with Capistrano > 3.7.0. Do you think that the Capistrano's dependency can be upgrade to the last release? I'm not very comfortable with Ruby to test it.
Thank you

**Comment by minimum2scp** [comment]
> but doesn't work with Capistrano >= 3.7.0

Really? Can you give me the error message, and the version of capistrano?

**Comment by 2ec0b4** [comment]
Hello,
Sorry, i made a mistake, i wanted to say "Capistrano > 3.7.0".

Here is the output when i try to setup my service:

```
$ cap production systemd:check_orders:setup
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `activate' for nil:NilClass
/var/www/capfile:8:in `<top (required)>'
Gem::ConflictError: Unable to activate capistrano-systemd-multiservice-0.1.0.beta1, because capistrano-3.8.2 conflicts with capistrano (~> 3.7.0)
/var/www/capfile:8:in `<top (required)>'
LoadError: cannot load such file -- capistrano/systemd/multiservice
/var/www/capfile:8:in `<top (required)>'
(See full trace by running task with --trace)

$ cap -v
Capistrano Version: 3.8.2 (Rake Version: 10.4.2)
```

Thank you

**Comment by minimum2scp** [comment]
OK, I understood.
I will relax the gem dependency and release new version.
Please wait a few days.

**Comment by minimum2scp** [comment]
@2ec0b4 
Released [0.1.0.beta2](https://rubygems.org/gems/capistrano-systemd-multiservice/versions/0.1.0.beta2), please update and try.

**Comment by 2ec0b4** [comment]
👍
